spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backend
    username: root
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    username: cohort47project@gmail.com
    password: cohort47@2024
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


